### ISSUE TITLE
Support for Sass mixin syntax highlighting

### ISSUE THREAD

**Issue by tomgenoni** [jacobrask/styledocco#22]
First, this is a great little tool. Thanks much for creating it.

The only issue I've found so far is that while this will output to the code view with proper syntax highlighting:

```
 a {    
     color: $platform-color;
  }
```

This will not:

```
 a {    
     color: $platform-color;
     @include foo;
  }
```

It appears blocks with mixin declarations often kill the syntax highlighting for that entire block of code. But it seems to work in other places so I'm not exactly sure what the root cause is.

**Comment by jacobrask** [comment]
Hi, the problem is that the Highlight.js script that StyleDocco is using does not support SASS. The SASS parts that are syntax highlighted are mostly by "accident" as Highlight.js consider it to be plain CSS.

Unfortunately I have not found any JavaScript syntax highlighters (neither Node.js nor client side) with SASS support. It might not be that difficult to add SASS support to Highlight.js, but I doubt I will have time for that unfortunately.

**Comment by tomgenoni** [comment]
Ah, that makes sense.Thanks for the quick reply. 

I was wondering then what would be your the recommended way to disable the syntax highlighting in styledocco? I've been using rainbow.js lately and though it doesn't officially support Sass (SCSS) it's close enough.

**Comment by jacobrask** [comment]
I have now disabled the syntax highlighting output, and will add a client side solution later instead.
