### ISSUE TITLE
Need some pointers

### ISSUE THREAD

**Issue by MarcDiethelm** [jacobrask/styledocco#61]
So I forked and cloned Styledocco. It really is just what I need and I want to be able to hack, adapt and possibly help improve it. But as it turns out I have no idea how to run it from the working copy. Can you give me some pointers? I feel stupid right now.

**Comment by jacobrask** [comment]
Hi, cool!

I might've integrated my dev branch into master a bit prematurely, but the master branch is now the development branch for a new client-side version of StyleDocco. All sources for that live in web/. To use it, edit dist/index.html with your config options and open index.html on a web server.

It currently only has support for regular CSS and has to be hosted on a web server due to cross-origin issues on file://. A "precompilation" step for preprocessors and file:// support will be added as soon as I get time, which might be a couple of weeks unfortunately. 

If you want to hack on the version currently in npm, work on the v0.6 mtainenace branch. I expect some people to prefer that branch since the new one has quite a lot of changes, so I might keep maintaining that as well, or encourage someone else to.

**Comment by MarcDiethelm** [comment]
Hey thanks for the quick reply!
Hmm, there's no dist folder in master after cloning. So I don't know where to begin. Hosting through a Node.js http server is not a problem for me though.
I then tried using 0.6 like so  `node -n "Test" -o test_out test_in`. But nothing happened.

Basically I just need to 'see' Styledocco in action for now. Throw it some HTML/CSS snippets, generate the documentation and play with the output, including the HTML/CSS of the documentation itself.

In a nutshell my use is case is this: I need to get away from web style guides produced by designers, which are often meaningless for a frontend developer (at least for basic typography, buttons, forms and so on). I need to generate a basic frontend style guide from collaboratively created HTML/CSS snippets. I need the designers to be able to verify the output and frontend engineers to use it as a reference. It should be easy to update and generate the documentation. Oh and last but not least: I need lessCSS support.

So far so good. Styledocco seems to provide all this. :) But I can't seem to get started.

**Comment by MarcDiethelm** [comment]
I'm sorry to bother you. But I'm extremely interested in this project. I'm really hoping you can help me out.

**Comment by marrs** [comment]
Presuming you have cloned styledocco to `~/styledoco`, the executable lives in `~/styledocco/bin/styledocco`.  If you have css files in `~/website/css` and your working directory is `~/website`, you should be able to get started with `~/styledocco/bin/styledocco css`.

**Comment by marrs** [comment]
Closing for now. Feel free to reopen if you still need help
